name: proseekr
description: A job portal for blue-collars
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # local storage
  shared_preferences: ^0.5.6

  # firebase packages
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.1
  firebase_database: ^3.1.0
  firebase_storage: ^3.0.8
  firebase_messaging: ^6.0.2
  cloud_firestore: ^0.13.0+1

  # component library
  fluttertoast: ^3.1.3

  # file and image libraries
  file_picker:
  image_cropper: 1.0.2
  image_picker: 0.6.0+17

  # misc
  keyboard_avoider:
  validators: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/children_with_bananas_lq.jpg