name: proseekr
description: A communication platform for blue-collar job seekers and providers
version: 1.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # firebase packages
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.1
  firebase_database: ^3.1.0
  firebase_storage: ^3.0.8
  firebase_messaging: ^6.0.2
  cloud_firestore: ^0.13.0+1

  # component library
  fluttertoast: ^3.1.3
  auto_size_text:

  # file and image libraries
  file_picker:
  image_picker: 0.6.0+17

  # i18n/i10n dependencies
  flutter_localizations:
    sdk: flutter

  # misc
  keyboard_avoider:
  validators: ^2.0.0+1
  shared_preferences: ^0.5.6
  flutter_tts: 0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/children_with_bananas_lq.jpg
    - assets/locale/localization_en.json
    - assets/locale/localization_hi.json
    - assets/locale/localization_te.json