name: proseekr
description: A job portal for blue-collars.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.1
  firebase_database: ^3.1.0
  firebase_storage: ^3.0.8
  firebase_messaging: ^6.0.2
  fluttertoast: ^3.1.3
  image_cropper: 1.0.2
  image_picker: 0.6.0+17
  cloud_firestore:
  keyboard_avoider:
  file_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  validators: ^2.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/children_with_bananas_lq.jpg